version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "3001:3000"
